### PR TITLE
Bump to ^0.4

### PR DESCRIPTION
**Pull request by covingtondoan**

### CODE REVIEW

**Comment by erquhart** [comment]
Docs are actually generated from the netlify-cms repo, where an 0.4 bump PR is already pending merge - not sure why we left these unused static files in place, or if it hurts anything to remove them.

I'm good with merging for the admin bump, though, no change necessary.

**Comment by verythorough** [comment]
As I recall, we have the docs files in here because they're used with Markdown Magic to pull the file content from netlify-cms. However, it's probably a good idea to remove the text from those files that was in place before we implemented Markdown Magic.

@erquhart Do we need to worry about the yarn.lock change?

**Comment by erquhart** [comment]
No, yarn.lock change is fine.

**Comment by verythorough** [comment]
This will be superceded by #28, but I merged anyway so @covingtondoan can get the green square. :) Thanks for the fix!

**Pull request merged**
