### PR TITLE
Algolia Docsearch Fix

### PR DESCRIPTION
**Pull request by eliwilliamson**
Fix the broken search input in the header. This should close issue #18

### CODE REVIEW

**Comment by eliwilliamson** [comment]
@bdougie do you mind fixing the search functionality?

**Comment by bdougie** [comment]
Looks like there an update to Algolia's docsearch causing dosearch to be undefined. I opened an issue. 

screenshot 2017-03-27 08 47 32


https://github.com/algolia/docsearch/issues/175

**Comment by bdougie** [comment]
referencing #18

**Comment by eliwilliamson** [comment]
@bdougie still isn't showing any results and it looks like the - top-padding is messed up now. Additionally, i'm not a fan of the logo/verbiage change to the 'fork me on github' button. it isn't very readable and the icon didn't load right away for me so it just read 'fork me on'.

**Comment by bdougie** [comment]
I forgot I changed that and just changed it back. The padding was fixed as well and might need a hard fresh to see the search work. 

ezgif com-video-to-gif 5

**Comment by eliwilliamson** [comment]
@bdougie the search dropdown seems to be working now but the padding is still off. the baselines (green and red lines) should be algned. the padding top and bottom should be the same (see the blue boxes).
screen shot 2017-03-27 at 2 36 10 pm
screen shot 2017-03-27 at 2 36 01 pm

**Comment by bdougie** [comment]
Do you mind if I add flexbox to this page?

**Comment by eliwilliamson** [comment]
@bdougie not at all 👍

**Comment by bdougie** [comment]
Can I get feedback on this @eliwilliamson. I did not go with flexbox, there would of been too much need to be written. 

screenshot 2017-04-12 07 26 51

**Comment by verythorough** [comment]
Looking forward to having searchable docs! A few nitpicks:
 * The search input is 1px shorter in height than the GitHub button
 * The input doesn't have a screenreader-accessible label
 * It would be nice to have search on mobile, though I know this would require more significant changes.
 * In a small width range around 660px, the layout gets a bit janky:
screen shot 2017-04-12 at 8 31 42 am

**Comment by bdougie** [comment]
@verythorough what browser and is this windows you are seeing this on? Mobile will have to wait for now. Algolia has given us 10 days before they kill the integration since it is currently not in production. 

I just pushed a larger break point fix, but I will work on a better solution for that weirdness. I also added a `type="search"` to the input.

**Comment by bdougie** [comment]
@verythorough I pushed more updates, let me know if anything else is lingering that needs addressing:

https://adds-algolia-search-to-page--netlify-cms-www.netlify.com/

screenshot 2017-04-12 10 03 43

**Comment by verythorough** [comment]
Hm, the preview looked like it had built OK when I reviewed. Now that it's broken, I think the new spacing on the svg may be borking it.

**Comment by bdougie** [comment]
Looks good now. The error wasn't very clear but concerning

**Comment by verythorough** [comment]
I ran it through svgomg while I was looking for spacing errors. reduces the size by 45% of you want to use the modified code:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56.966 56.966" width="16" height="12">
  <path d="M55.146 51.887l-13.558-14.1c3.486-4.145 5.396-9.36 5.396-14.787 0-12.682-10.318-23-23-23s-23 10.318-23 23 10.318 23 23 23c4.76 0 9.298-1.436 13.177-4.162l13.662 14.208c.57.593 1.34.92 2.162.92.78 0 1.518-.297 2.08-.837 1.19-1.148 1.23-3.05.082-4.243zM23.984 6c9.374 0 17 7.626 17 17s-7.626 17-17 17-17-7.626-17-17 7.626-17 17-17z" fill="#FFF"/>
</svg>
```

**Comment by verythorough** [comment]
Otherwise, I'm good. 👍

**Comment by eliwilliamson** [comment]
@bdougie LGTM 👍

**Comment by calavera** [comment]
@bdougie I'm seeing duplicated search results, I'm not sure if it's us or algolia. Do you know why that happens?

screenshot from 2017-04-18 18-30-31

**Comment by bdougie** [comment]
I believe it is because the docsearch api scrapes the page and the titles appear on the page twice. Once in the menu and another time in the header. This project is open sourced and I can reach out to see if this can be tweaked.

**Pull request merged**
