### PR TITLE
relocate docs content to cms-www repo

### PR DESCRIPTION
**Pull request by erquhart**

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 8f7e9f28fe81cda337ed9f9f17bfd812424505a0

https://deploy-preview-58--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
Are we going to be migrating all the docs PRs (and issues) from the main repo to here?

**Comment by verythorough** [comment]
👍 LGTM! Looking forward to simpler previews for docs edits.

We'll need to handle the changes inhttps://github.com/netlify/netlify-cms/pull/751 - either add them to this PR, or make a new PR in this repo after this one is merged.

**Comment by tech4him1** [comment]
There are a couple smaller ones as well, netlify/netlify-cms#585 and netlify/netlify-cms#823, but they could be moved easily.

**Comment by erquhart** [comment]
I'll include the auth changes from @verythorough now, the other two that @tech4him1 mentioned can be PR'd separately.

**Pull request merged**
